export const SUBMIT_LOGIN_FORM = 'SUBMIT_LOGIN_FORM';
export const CLEAR_LOGIN_FORM = 'CLEAR_LOGIN_FORM';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const HANDLE_LOGIN_INPUT_FORM = 'HANDLE_LOGIN_INPUT_FORM';
export const INPUT_FORM_VALIDATION_SUCCESS = 'INPUT_FORM_VALIDATION_SUCCESS';
export const INPUT_FORM_VALIDATION_FAILURE = 'INPUT_FORM_VALIDATION_FAILURE';
